### ISSUE TITLE
Load Pictures

### ISSUE THREAD

**Issue by MatteoJoliveau** [jemcode/administrate-field-ckeditor#14]
Hello, thanks for this project!

More of a question than an issue, I have a Rails 5.2 application with ActiveStorage to upload images to S3. 
Is there a way to configure it directly from the field or should I customize CKEditor's JavaScript, in order to have the following screen upload the images and retrieve them via ActiveStorage?

**Comment by rikkipitt** [comment]
Hi @MatteoJoliveau, I'm in the same boat as you.

I'm currently watching these two issues on the `galetahub/ckeditor` gem: 

- https://github.com/galetahub/ckeditor/issues/795
- https://github.com/galetahub/ckeditor/issues/805

It looks like ActiveStorage support is on the radar. I can't see any specific branches yet though...
