### ISSUE TITLE
I want to add the lineheight config option

### ISSUE THREAD

**Issue by drewpterry** [jemcode/administrate-field-ckeditor#15]
Is it possible to use add ons with this gem? ie https://ckeditor.com/cke4/addon/lineheight

**Comment by rikkipitt** [comment]
Hi @drewpterry, the underlying ckeditor gem is configurable. You can find more information on customisation (including adding plugins) here: https://github.com/galetahub/ckeditor

Specifically:
https://github.com/galetahub/ckeditor#install-additional-plugins

Let me know how you get on!
Rikki
