### ISSUE TITLE
Will the production gem support administrate version > 0.8?

### ISSUE THREAD

**Issue by imgarylai** [jemcode/administrate-field-ckeditor#7]
Will you push your latest update to rubygems.org? I have this question because I fail to install this gem from source. The reason is the rubygem one restricting administrate version under 0.8 and my administrate version is 0.8.1. However, in your gemspec, it shows this gem is available upto 0.9.

https://github.com/jemcode/administrate-field-ckeditor/blob/efe516a14e667a5aaf26c6b9db0a87c726e4c902/administrate-field-ckeditor.gemspec#L17

Hope you have plan to support this gem to newer administrate version. Thanks!

**Comment by rikkipitt** [comment]
Hi Gary, thanks for pointing this out. It looks like I forgot to release the dependency updates to RubyGems.org!

This should all be in order now. Do you mind confirming if you get a moment?

**Comment by imgarylai** [comment]
It's on latest dependency now. Thank you!

**Comment by rikkipitt** [comment]
Thanks @imgarylai!
