### ISSUE TITLE
enhancement for the ckeditor width

### ISSUE THREAD

**Issue by sobanakram** [jemcode/administrate-field-ckeditor#8]
enhancement for the ckeditor width for better UX.
For now it shows ckeditor as other fields width (45%) in administrate.
<img width="1095" alt="screen shot 2017-12-11 at 2 01 35 pm" src="https://user-images.githubusercontent.com/10559510/33823163-e468c41e-de7b-11e7-8b22-23579793ef92.png">

It is best if we change it to auto or max we can. Like this
<img width="1096" alt="screen shot 2017-12-11 at 2 03 42 pm" src="https://user-images.githubusercontent.com/10559510/33823215-1fa1b3f6-de7c-11e7-9e6a-c7c0487c70de.png">
#

**Comment by rikkipitt** [comment]
Sounds good to me. I'll look into adding it to a stylesheet when I get 5 minutes.

Thanks for the suggestion!
